# Generated by Django 5.2.1 on 2025-06-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_remove_membershipplan_perks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='membership.membershipplan', verbose_name='Membership Plan'),
        ),
    ]
