# Generated by Django 5.2.1 on 2025-06-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('cafe_description', models.TextField()),
                ('cafe_address', models.TextField(default='')),
                ('map_url', models.URLField(default='', max_length=1000)),
                ('cafe_location', models.CharField(max_length=200)),
                ('branch_manager_name', models.CharField(max_length=200)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=200)),
                ('website_url', models.URLField()),
                ('cafe_speciality', models.TextField(default='')),
                ('terms_accepted', models.BooleanField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Cafe',
                'verbose_name_plural': 'Cafes',
            },
        ),
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cafe_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe.cafe')),
            ],
            options={
                'verbose_name': 'Cafe Image',
                'verbose_name_plural': 'Cafe Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CafeHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.CharField(max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text="Optional: Manually specify icon class (e.g., 'fa-wifi'). If left blank, an icon will be inferred from highlight text if mapped.", max_length=50, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=1)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='cafe.cafe')),
            ],
            options={
                'verbose_name': 'Cafe Highlight',
                'verbose_name_plural': 'Cafe Highlights',
                'ordering': ['order'],
                'unique_together': {('cafe', 'highlight_text')},
            },
        ),
    ]
