# Generated by Django 5.2.1 on 2025-06-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='cafe_speciality',
            new_name='cafe_specialty',
        ),
    ]
