# Generated by Django 5.2.1 on 2025-06-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_rename_cafe_speciality_cafe_cafe_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='terms_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
