# Generated by Django 5.2.1 on 2025-06-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_cafe_terms_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='terms_accepted',
        ),
    ]
