# Generated by Django 5.2.1 on 2025-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_cafe_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='terms_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
