# Generated by Django 5.2.1 on 2025-06-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_cafe_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
