# Generated by Django 5.2.1 on 2025-06-13 14:23

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_cafereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=10)),
                ('location_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='location_name', unique=True)),
            ],
        ),
    ]
