# Generated by Django 5.2.1 on 2025-06-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='CafeLocation',
        ),
    ]
