# Generated by Django 5.2.1 on 2025-06-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_rename_location_cafelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cafe.cafelocation'),
        ),
    ]
