# Generated by Django 5.2.1 on 2025-07-18 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_cafe_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='image',
            field=models.ImageField(upload_to='cafe_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
    ]
