# Generated by Django 5.2.1 on 2025-07-18 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_alter_cafeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='image',
            field=models.ImageField(upload_to='cafe_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
