# Generated by Django 5.2.1 on 2025-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_alter_cafeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
