# Generated by Django 5.2.1 on 2025-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_cafe_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_cafe_of_the_week',
            field=models.BooleanField(default=False),
        ),
    ]
