# Generated by Django 5.2.1 on 2025-07-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_cafe_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafereview',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Admin can pick up to 3 as best/featured.'),
        ),
    ]
