# Generated by Django 5.2.1 on 2025-07-31 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0016_cafereview_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cafe': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafes', to=settings.AUTH_USER_MODEL),
        ),
    ]
